### ISSUE TITLE
Convert all components using ember-composability-tools to glimmer

### ISSUE THREAD

**Issue by matthewhartstonge** [adopted-ember-addons/ember-paper#1292]
# Todo

## Mixins
There are a number of mixins that each of these components extend from which will need to be unwound as part of the work.
- [x] ColorMixin https://github.com/adopted-ember-addons/ember-paper/pull/1293
- [x] EventsMixin https://github.com/adopted-ember-addons/ember-paper/pull/1294
- [ ] FocusableMixin
- [ ] ChildMixin
- [ ] ParentMixin
- [ ] ProxiableMixin

## Parent Components
- [x] paper-form https://github.com/adopted-ember-addons/ember-paper/pull/1300
- [x] paper-grid-list https://github.com/adopted-ember-addons/ember-paper/pull/1299
- [x] paper-item https://github.com/adopted-ember-addons/ember-paper/pull/1304
- [x] paper-radio-group https://github.com/adopted-ember-addons/ember-paper/pull/1309
- [ ] paper-tabs

## Children Components
- [x] paper-grid-tile https://github.com/adopted-ember-addons/ember-paper/pull/1299
- [ ] paper-input
- [x] paper-radio https://github.com/adopted-ember-addons/ember-paper/pull/1309
- [ ] paper-select
- [ ] paper-tab

## Proxiable Components
- [x] paper-button https://github.com/adopted-ember-addons/ember-paper/pull/1298
- [x] paper-checkbox https://github.com/adopted-ember-addons/ember-paper/pull/1305
- [x] paper-radio-proxiable https://github.com/adopted-ember-addons/ember-paper/pull/1309
- [x] paper-switch

Understanding the hierarchy:

![Image](https://github.com/user-attachments/assets/f8299446-8ac5-4bff-95d3-eee5f9347ed3)

## native ember

The following on ember-render-modifiers gives an example of how to migrate these components using ember/glimmer native primitives and patterns

https://github.com/emberjs/ember-render-modifiers#example-ember-composability-tools-style-rendering

## PR Ordering

I've 'stacked' these PRs to minimise the amount needed to be reviewed, but each item requires the changes made before:

- https://github.com/adopted-ember-addons/ember-paper/pull/1293
- https://github.com/adopted-ember-addons/ember-paper/pull/1294
- https://github.com/adopted-ember-addons/ember-paper/pull/1298
- https://github.com/adopted-ember-addons/ember-paper/pull/1299
- https://github.com/adopted-ember-addons/ember-paper/pull/1300
- https://github.com/adopted-ember-addons/ember-paper/pull/1304
- https://github.com/adopted-ember-addons/ember-paper/pull/1305
- https://github.com/adopted-ember-addons/ember-paper/pull/1309
- https://github.com/adopted-ember-addons/ember-paper/pull/1310

**Comment by matthewhartstonge** [comment]
There are a number of mixins that each of these components extend from which will need to be unwound as part of the work.

- [ ] ChildMixin
- [ ] ColorMixin
- [ ] EventsMixin
- [ ] FocusableMixin
- [ ] ParentMixin
- [ ] ProxiableMixin

**Comment by matthewhartstonge** [comment]
Understanding the current hierarchy:

![image](https://github.com/user-attachments/assets/b4a3e584-86dd-44c9-b241-284b48497ab6)
